version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartvigilant_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ai_engine:/app/models
    environment:
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartvigilant_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
